name:                         Rust test

on:
  pull_request:
  push:
    branches:
      - main 

jobs:
  check:
    name:                     Cargo nextest
    runs-on:                  ubuntu-latest
    steps:

      - name:                 Cancel Previous Runs
        uses:                 styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 # 0.11.0
        with:
          access_token:       ${{ github.token }}

      - name:                 Checkout sources
        uses:                 actions/checkout@v3
        with:
          fetch-depth:        50
          submodules:         'recursive'

      - name:                 Install Rust stable toolchain
        uses:                 actions-rs/toolchain@v1
        with:
          profile:            minimal
          toolchain:          stable
          override:           true

      - name:                 Install cargo-nextest
        uses:                 baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f # v1.3.0
        with:
          crate:              cargo-nextest
          version:            0.9

      - name:                 Rust Cache
        uses:                 Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
        with:
          working-directory:  .

      - name:                 cargo nextest
        run:                  cargo nextest run
